// packages/doc-cli/src/template/react/components/demo.tsx
import { type PropsWithChildren, useEffect } from 'react'

interface props {
  code: string
}

const Demo = (props: PropsWithChildren<props>) => {
  useEffect(() => {
    window.hljs.highlightAll()
  }, [])
  return <div className='doc-cli-demo-container'>
    <div className='doc-cli-demo-render'>
      {props.children}
    </div>
    <div className='doc-cli-demo-code'>
      <pre className='language-tsx'>
        <code>
          {props.code}
        </code>
      </pre>
    </div>
    </div>
}

export default Demo

// packages/doc-cli/src/template/vue/components/Demo/index.vue
<script setup lang="ts">
import { onMounted } from 'vue'

const props = defineProps(['code'])
onMounted(() => {
  window.hljs.highlightAll()
})
</script>

<template>
  <div>
    <div>demo</div>
    <slot />
    <div>
      <pre class="language-html">
        <code>
          {{ props.code }}
        </code>
      </pre>
    </div>
  </div>
</template>
