// packages/doc-cli/src/template/react/layout/default.tsx
import type { PropsWithChildren } from 'react'

const DefaultLayout = (props: PropsWithChildren) => {
  return <div className="doc-layout-default">
  <div className="doc-layout-header">
    header
  </div>
  <div className="doc-layout-wrapper">
    <div className="doc-layout-sidebar">
      sidebar
    </div>
    <div className="doc-layout-content">
      {props.children}
    </div>
  </div>
</div>
}

export default DefaultLayout

// packages/doc-cli/src/template/vue/layout/Default.vue
<script setup lang="ts">
</script>

<template>
  <div class="doc-layout-default">
    <div class="doc-layout-header">
      header
    </div>
    <div class="doc-layout-wrapper">
      <div class="doc-layout-sidebar">
        sidebar
      </div>
      <div class="doc-layout-content">
        <slot />
      </div>
    </div>
  </div>
</template>
